### ISSUE TITLE
Error when running lein repl

### ISSUE THREAD

**Issue by jbalaty** [sattvik/async-workshop#3]
Hello,

sorry for bothering, but the project does not work for me. I think I proceeded according to tutorial, but when I run "lein repl" I get this error:

Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Projects-git/async-works
hop/resources/templates/index.html, compiling:(C:\Users\balaty\AppData\Local\Temp\form-init4082947376693409680.clj:1:126
)
        at clojure.lang.Compiler.load(Compiler.java:7196)
        at clojure.lang.Compiler.loadFile(Compiler.java:7140)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Projects-git/async-workshop/resources/te
mplates/index.html
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at net.cgrand.reload$eval14623$fn__14624.invoke(reload.clj:51)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at net.cgrand.reload$auto_reload.invoke(reload.clj:10)
        at clojure.core$comp$fn__4292.invoke(core.clj:2434)
        at clojure.core$map$fn__4345.invoke(core.clj:2612)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:135)
        at clojure.core$dorun.invoke(core.clj:2992)
        at user$start.invoke(user.clj:75)
        at user$eval15412.invoke(form-init4082947376693409680.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6757)
        at clojure.lang.Compiler.eval(Compiler.java:6747)
        at clojure.lang.Compiler.eval(Compiler.java:6746)
        at clojure.lang.Compiler.load(Compiler.java:7184)
        ... 11 more
REPL server launch timed out.

My platform is Windows7
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
Leiningen 2.3.4 on Java 1.8.0_05 Java HotSpot(TM) 64-Bit Server VM

Thx for any advice

**Comment by twigington** [comment]
I'm running into the same problem. This seems to be related to this enlive bug. https://github.com/cgrand/enlive/issues/92
